default_agent: kb_agent
agents:
  kb_agent:
    name: kb_agent
    language: python
    node_version: null
    entrypoint: /workshop/2-kb-agent/kb_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::223609046142:role/AgentCoreRuntimeRole
      execution_role_auto_create: false
      account: '223609046142'
      region: us-west-2
      ecr_repository: 223609046142.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-kb_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: kb_agent-n2PpEEA2Oc
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:223609046142:runtime/kb_agent-n2PpEEA2Oc
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-kb_agent-builder
      execution_role: arn:aws:iam::223609046142:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-f1e860203a
      source_bucket: bedrock-agentcore-codebuild-sources-223609046142-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
